Models/Reserveringen.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace D_Einder_MVC.Models
{
    public class Reserveringen
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Date")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }

        public string  Tijd { get; set; }

        public string Naam { get; set; }

        public string Adress { get; set; }

        public string Woonplaats { get; set; }
      
        public int TafelId { get; set; }

        [ForeignKey("TafelId")]
        public Tafel Tafel { get; set; }

        public IList<Order> Order { get; set; }


    }
}

Controllers/ReserveringensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using D_Einder_MVC.Data;
using D_Einder_MVC.Models;
using Microsoft.Extensions.Primitives;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace D_Einder_MVC.Controllers
{
    public class ReserveringensController : Controller
    {
        private readonly DataDbContext _context;

        public ReserveringensController(DataDbContext context)
        {
            _context = context;
        }


        [Authorize(Roles = "Personeel,Manager,SUPERADMIN")]
        // GET: Reserveringens
        public async Task<IActionResult> Index()
        {
            var dataDbContext = _context.Reserveringen.Include(r => r.Tafel);
            return View(await dataDbContext.ToListAsync());
        }

        public async Task<IActionResult> Index2()
        {
            var dataDbContext = _context.Reserveringen.Include(r => r.Tafel);
            return View(await dataDbContext.ToListAsync());
        }

        [Authorize(Roles = "Personeel,Manager,SUPERADMIN")]
        public ActionResult IndexReserveringen()
        {
            var viewModel = new IndicatorViewModel
            {
                Reservaties = _context.Reserveringen.ToList(),
                Tafels = _context.Tafel.ToList()
            };
            return View("IndexReserveringen", viewModel);
        }


        [Authorize(Roles = "Personeel,Manager,SUPERADMIN")]
        // GET: Reserveringens/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserveringen = await _context.Reserveringen
                .Include(r => r.Tafel)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reserveringen == null)
            {
                return NotFound();
            }

            ViewData["Orders"] = _context.Order.Where(o => o.ReserveringenId == id).ToList();
            return View(reserveringen);
        }


        // GET: Reserveringens/Create
        public IActionResult Create()
        {
            List<SelectListItem> items = new List<SelectListItem>();

            items.Add(new SelectListItem { Text = "8:30 - 9:00", Value = "8:30 - 9:00" });

            items.Add(new SelectListItem { Text = "9:00 - 9:30", Value = "9:00 - 9:30" });

            items.Add(new SelectListItem { Text = "9:30 - 10:00", Value = "9:30 - 10:00" });

            items.Add(new SelectListItem { Text = "10:00 - 10:30", Value = "10:00 - 10:30" });

            items.Add(new SelectListItem { Text = "10:30 - 11:00", Value = "10:30 - 11:00" });

            items.Add(new SelectListItem { Text = "11:00 - 11:30", Value = "11:00 - 11:30" });

            items.Add(new SelectListItem { Text = "11:30 - 12:00", Value = "11:30 - 12:00" });

            items.Add(new SelectListItem { Text = "12:00 - 12:30", Value = "12:00 - 12:30" });

            items.Add(new SelectListItem { Text = "12:30 - 1:00", Value = "12:30 - 1:00" });

            items.Add(new SelectListItem { Text = "1:00 - 1:30", Value = "1:00 - 1:30" });

            items.Add(new SelectListItem { Text = "1:30 - 2:00", Value = "1:30 - 2:00" });

            items.Add(new SelectListItem { Text = "2:00 - 2:30", Value = "2:00 - 2:30" });

            items.Add(new SelectListItem { Text = "2:30 - 3:00", Value = "2:30 - 3:00" });

            items.Add(new SelectListItem { Text = "3:00 - 3:30", Value = "3:00 - 3:30" });

            items.Add(new SelectListItem { Text = "3:30 - 4:00", Value = "3:30 - 4:00" });

            items.Add(new SelectListItem { Text = "4:00 - 4:30", Value = "4:00 - 4:30" });

            items.Add(new SelectListItem { Text = "4:30 - 5:00", Value = "4:30 - 5:00" });

            items.Add(new SelectListItem { Text = "5:00 - 5:30", Value = "5:00 - 5:30" });

            items.Add(new SelectListItem { Text = "5:30 - 6:00", Value = "5:30 - 6:00" });


            ViewBag.Tijd = items;


            ViewData["TafelId"] = new SelectList(_context.Tafel, "Id", "Naam");
            ViewData["Menus"] = _context.Menu.ToArray();
            return View();
        }

        // POST: Reserveringens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Date,Tijd,Naam,Adress,Woonplaats,TafelId")] Reserveringen reserveringen)
        {
            ViewBag.ErrorMessage = "";
            if (ModelState.IsValid)
            {
                var tafeltijd = _context.Reserveringen.FirstOrDefault(x => x.TafelId == reserveringen.TafelId);

                if (tafeltijd == null)
                _context.Add(reserveringen);
                await _context.SaveChangesAsync();

                foreach (Menu menu in _context.Menu.ToArray())
                {
                    if (Request.Form.TryGetValue($"menu[{menu.Id}]", out StringValues menuAmount))
                    {
                        if (menuAmount.Any() && int.TryParse(menuAmount, out int amount))
                        {
                            if (amount == 0)
                                continue;

                            Order order = new()
                            {
                                //Id = (_context.Order.Last().Id + 1),
                                ReserveringenId = reserveringen.Id,
                                MenuNaam = menu.Naam,
                                Menu = menu,
                                Hoeveelheid = amount
                            };

                            _context.Order.Add(order);
                            await _context.SaveChangesAsync();
                        }
                    }
                }

                return RedirectToAction(nameof(Index2));
            }
            


            ViewData["TafelId"] = new SelectList(_context.Tafel, "Id", "Naam", reserveringen.TafelId);
            return View(reserveringen);
        }

        
        // GET: Reserveringens/Edit/5
        [Authorize(Roles = "Personeel,Manager,SUPERADMIN")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserveringen = await _context.Reserveringen.FindAsync(id);
            if (reserveringen == null)
            {
                return NotFound();
            }

            List<SelectListItem> items = new List<SelectListItem>();

            items.Add(new SelectListItem { Text = "8:30 - 9:00", Value = "8:30 - 9:00" });

            items.Add(new SelectListItem { Text = "9:00 - 9:30", Value = "9:00 - 9:30" });

            items.Add(new SelectListItem { Text = "9:30 - 10:00", Value = "9:30 - 10:00" });

            items.Add(new SelectListItem { Text = "10:00 - 10:30", Value = "10:00 - 10:30" });

            items.Add(new SelectListItem { Text = "10:30 - 11:00", Value = "10:30 - 11:00" });

            items.Add(new SelectListItem { Text = "11:00 - 11:30", Value = "11:00 - 11:30" });

            items.Add(new SelectListItem { Text = "11:30 - 12:00", Value = "11:30 - 12:00" });

            items.Add(new SelectListItem { Text = "12:00 - 12:30", Value = "12:00 - 12:30" });

            items.Add(new SelectListItem { Text = "12:30 - 1:00", Value = "12:30 - 1:00" });

            items.Add(new SelectListItem { Text = "1:00 - 1:30", Value = "1:00 - 1:30" });

            items.Add(new SelectListItem { Text = "1:30 - 2:00", Value = "1:30 - 2:00" });

            items.Add(new SelectListItem { Text = "2:00 - 2:30", Value = "2:00 - 2:30" });

            items.Add(new SelectListItem { Text = "2:30 - 3:00", Value = "2:30 - 3:00" });

            items.Add(new SelectListItem { Text = "3:00 - 3:30", Value = "3:00 - 3:30" });

            items.Add(new SelectListItem { Text = "3:30 - 4:00", Value = "3:30 - 4:00" });

            items.Add(new SelectListItem { Text = "4:00 - 4:30", Value = "4:00 - 4:30" });

            items.Add(new SelectListItem { Text = "4:30 - 5:00", Value = "4:30 - 5:00" });

            items.Add(new SelectListItem { Text = "5:00 - 5:30", Value = "5:00 - 5:30" });

            items.Add(new SelectListItem { Text = "5:30 - 6:00", Value = "5:30 - 6:00" });


            ViewBag.Tijd = items;



            ViewData["TafelId"] = new SelectList(_context.Tafel, "Id", "Naam", reserveringen.TafelId);
            ViewData["Menus"] = _context.Menu.ToArray();
            return View(reserveringen);
        }



        // POST: Reserveringens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [Authorize(Roles = "Personeel,Manager,SUPERADMIN")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date,Tijd,Naam,Adress,Woonplaats,TafelId")] Reserveringen reserveringen)
        {
            if (id != reserveringen.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                var tafeltijd = _context.Reserveringen.FirstOrDefault(x => x.TafelId == reserveringen.TafelId);

                if (tafeltijd == null)
                    _context.Update(reserveringen);
                await _context.SaveChangesAsync();

                foreach (Menu menu in _context.Menu.ToArray())
                {
                    if (Request.Form.TryGetValue($"menu[{menu.Id}]", out StringValues menuAmount))
                    {

Views/Reserveringens/Create.cshtml
@model D_Einder_MVC.Models.Reserveringen

@{
    ViewData["Title"] = "Create";
}

@{
    if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
    {
        <div class="margi">
            <div class="btn btn-danger">
                <p>
                    <h3>@Html.Raw(ViewBag.ErrorMessage)</h3>
                </p>
            </div>
        </div>
    }
    @Html.AntiForgeryToken()
}

<div class="margin2"></div>
<div class="flex-container-reserveer">
    <div class="flex-item-left-reserveer">
        <div class="main_inlog_border_four">
            <h1>Reserveer!</h1>
            <h4 class="text-info">Vul je gegevens in</h4>
            <hr />
            <div class="row">
                <div class="col-md-10">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Date" class="control-label"></label>
                            <input asp-for="Date" class="form-control" />
                            <span asp-validation-for="Date" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Tijd" class="control-label"></label>
                            <select asp-for="Tijd" class="form-control" asp-items="ViewBag.Tijd"></select>
                        </div>
                        <div class="form-group">
                            <label asp-for="Naam" class="control-label"></label>
                            <input asp-for="Naam" class="form-control" />
                            <span asp-validation-for="Naam" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Adress" class="control-label"></label>
                            <input asp-for="Adress" class="form-control" />
                            <span asp-validation-for="Adress" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Woonplaats" class="control-label"></label>
                            <input asp-for="Woonplaats" class="form-control" />
                            <span asp-validation-for="Woonplaats" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="TafelId" class="control-label"></label>
                            <select asp-for="TafelId" class="form-control" asp-items="ViewBag.TafelId"></select>
                        </div>

                        <div class="main_inlog_border_four">
                            <h1>Kies een menu uit!</h1>
                            <h4 class="text-info">Vul een aantal menu's in</h4>
                            <hr />
                            <div class="row">
                                <div class="col-md-10">
                                    @foreach (var item in (IEnumerable<Menu>)ViewData["Menus"])
                                    {
                                        <div>
                                            <h3>@Html.DisplayFor(modelItem => item.Naam) </h3>
                                            <label>Prijs: @Html.DisplayFor(modelItem => item.Prijs) Euro </label><br />
                                            <label>Aantal</label>     <input placeholder="Hoeveelheid" type="number" min="0" name="menu[@Html.DisplayFor(modelItem => item.Id)]" maxlength="30" value="0">

                                        </div>

                                    }
                                    <br /> </br>
                                    <div class="form-group">
                                        <input type="submit" value="Create" class="btn btn-primary" />
                                    </div>
                    </form>
                </div>
                <div></div>

                <div>
                    <a asp-action="Index">Back to List</a>
                </div>

                @section Scripts {
                    @{
                        await Html.RenderPartialAsync("_ValidationScriptsPartial");
                    }
                }

Views/Reserveringens/Delete.cshtml
@model D_Einder_MVC.Models.Reserveringen

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div class="main_inlog_border_three">
    <h4>Reserveringen</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tijd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tijd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naam)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Woonplaats)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Woonplaats)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tafel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tafel.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Reserveringens/Details.cshtml
@model D_Einder_MVC.Models.Reserveringen

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div class="main_inlog_border_three">
    <h4>Reserveringen</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tijd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tijd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naam)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Woonplaats)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Woonplaats)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tafel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tafel.Id)
        </dd>
        @foreach (var item in (IEnumerable<Order>)ViewData["Orders"])
        {
            <dt class="col-sm-2">
                
                <h3>@Html.DisplayFor(modelItem => item.MenuNaam) </h3>
                <p>@Html.DisplayFor(modelItem => item.Hoeveelheid) keer besteld</p>
                
            </dt>

        }
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Reserveringens/Edit.cshtml
@model D_Einder_MVC.Models.Reserveringen

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Reserveringen</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tijd" class="control-label"></label>
                <select asp-for="Tijd" class="form-control" asp-items="ViewBag.Tijd"></select>
            </div>
            <div class="form-group">
                <label asp-for="Naam" class="control-label"></label>
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Woonplaats" class="control-label"></label>
                <input asp-for="Woonplaats" class="form-control" />
                <span asp-validation-for="Woonplaats" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TafelId" class="control-label"></label>
                <select asp-for="TafelId" class="form-control" asp-items="ViewBag.TafelId"></select>
                <span asp-validation-for="TafelId" class="text-danger"></span>
            </div>
                @foreach (var item in (IEnumerable<Menu>)ViewData["Menus"])
                {
                    <div>
                        <h3>@Html.DisplayFor(modelItem => item.Naam) </h3>
                        <p>@Html.DisplayFor(modelItem => item.Prijs)</p>
                        <input placeholder="Hoeveelheid" type="number" min="0" name="menu[@Html.DisplayFor(modelItem => item.Id)]" maxlength="30" value="0">

                    </div>

                }
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Reserveringens/Index.cshtml
@model IEnumerable<D_Einder_MVC.Models.Reserveringen>

@{
    ViewData["Title"] = "Index";
}

<h1>Reserveringen</h1>

<br />
<div class="box-button">
    <a class="btn nav-link text-dark border" asp-area="" asp-controller="Reserveringens" asp-action="IndexReserveringen"><h2>Aantal Reserveringen</h2></a>
</div>
<br />



<div class="p-4 border rounded">
    <p>
        <a asp-action="Create"><h2 class="btn btn-warning">Reservering Inplannen</h2></a>
        <a asp-controller="Orders" asp-action="TafelOverzicht"><h2 class="btn btn-info">Financiële Overzicht lijst</h2></a>
        <a asp-controller="Tafels" asp-action="IndexTafels"><h2 class="btn btn-light">Tafel Overzicht + Bestelde gerechten</h2></a>
    </p>

<table id="customers">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tijd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Naam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Adress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Woonplaats)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tafel)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tijd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Naam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Woonplaats)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tafel.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>

Views/Reserveringens/Index2.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="margi">
    <div class="btn btn-success">
        <p class="margiz">
            Uw tafel is gereserveerd</h3>
        </p>
    </div>
</div>
<hr />
<div class="text-center">
    <h1 class="ferdi">Welkom bij D'Einder !</h1>
    <div class="image-stock"><img src="~/images/restaurant-slider1.jpg" style="width:60%; height:275px"></div>
</div>

<div class="box-diner">
    <h2 class="diner-h">D'Einder Diner</h2>
    <p class="diner-p"> Verrassend eerlijke gerechten in een sfeervolle ambiance. Onze restaurant heeft de ideale locatie voor een uitgebreid diner.</p>
    <p class="diner-p"> In de Restaurant D'Einder bereiden onze ervaren keukenbrigades elke dag met plezier de lekkerste gerechten voor u klaar met dagverse ingrediënten.</p>

</div>
<br />



<!-- Tafel section -->
<div class="flex-container">
    <div class="flex-item-left">
        <h3 class="main-text-options">Reserveer een tafel</h3>
        <p class="small-options-text">U kunt hier online reserveren</p>
        <p> <a asp-controller="Reservaties" asp-action="Create"><h2 class="btn btn-warning">Reserveer</h2></a></p>
    </div>
    <div class=" flex-item-middle">
        <h3 class="main-text-options">Menukaart</h3>
        <p class="small-options-text">Bekijk hier onze menukaart</p>
        <a asp-controller="Menus" asp-action="Index2"><h2 class="btn btn-warning">Menukaart</h2></a>
    </div>

    <div class=" flex-item-right">
        <h3 class="main-text-options">Drinkenkaart</h3>
        <p class="small-options-text">Bekijk hier onze menukaart</p>
        <a asp-controller="Drinks" asp-action="Index2"><h2 class="btn btn-warning">Drinkenkaart</h2></a>
    </div>
</div>

<!-- Authenticator check section -->
<div class="text-center auto">
    @if (User.Identity.IsAuthenticated)
    {

        @if (User.IsInRole("Personeel"))
        {
            <h2>Your role is - Personeel</h2>
        }
        else
        {
            <h2>Your role is - Admin</h2>
        }
    }
</div>

Views/Reserveringens/IndexReserveringen.cshtml
@model D_Einder_MVC.Models.IndicatorViewModel


<br />
<br />
<h1>Aantal Reserveringen</h1>
<div class="margin"></div>
<table id="customers">
    <thead>
        <tr>
            <th>Aantal Reserveringen</th>

        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.Reservaties.Count(g => g.Naam == g.Naam) / @Model.Tafels.Count(g => g.Id == g.Id)</td>
        </tr>
    </tbody>
</table>
<hr />
<p><a class="btn btn-success" asp-area="" asp-controller="Reservaties" asp-action="Index">Terug</a> </p>